name: iorg_flutter
description: Image Filing Based General Utility Android Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #FIREBASE & LOGIN
  google_sign_in: ^4.5.3
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  firebase_core: "0.5.0"
  #UTILITY
  image: ^2.1.14
  animator: 0.1.4
  image_picker: ^0.6.7+7
  timeago: 2.0.17
  cached_network_image:
  geolocator: 5.0.1
  uuid: ^2.2.2
  path_provider: ^1.6.14
  font_awesome_flutter: ^8.8.1
  flutter_signin_button: ^1.1.0
  shared_preferences: ^0.5.10
  age: ^0.0.1
  intro_slider: ^2.3.2
  cupertino_icons: ^1.0.0
  fluttertoast: ^7.1.1


#dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/title.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
